package belfius.credit_risk.data.enrichment.entity;
// Generated Mar 15, 2022, 10:18:43 PM by Hibernate Tools 5.2.13.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Family generated by hbm2java
 */
@Entity
@Table(name = "FAMILY", schema = "PUBLIC")
public class Family implements java.io.Serializable {

	private Integer id;
	private String name;

	public Family() {
	}

	public Family(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
