package belfius.credit_risk.data.enrichment.entity;
// Generated Mar 15, 2022, 10:18:43 PM by Hibernate Tools 5.2.13.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rule generated by hbm2java
 */
@Entity
@Table(name = "RULE", schema = "PUBLIC")
public class Rule implements java.io.Serializable {

	@Id
	private int id;
	@Id
	private int version;
	private int statusId;
	private int familyId;
	private int scopeId;
	private int priority;
	private String sentence;
	private String description;

	public Rule() {
	}

	public Rule(int id, int version, int statusId, int familyId, int scopeId, int priority, String sentence) {
		this.id = id;
		this.version = version;
		this.statusId = statusId;
		this.familyId = familyId;
		this.scopeId = scopeId;
		this.priority = priority;
		this.sentence = sentence;
	}

	public Rule(int id, int version, int statusId, int familyId, int scopeId, int priority, String sentence, String description) {
		this.id = id;
		this.version = version;
		this.statusId = statusId;
		this.familyId = familyId;
		this.scopeId = scopeId;
		this.priority = priority;
		this.sentence = sentence;
		this.description = description;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "STATUS_ID", nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Column(name = "FAMILY_ID", nullable = false)
	public int getFamilyId() {
		return this.familyId;
	}

	public void setFamilyId(int familyId) {
		this.familyId = familyId;
	}

	@Column(name = "SCOPE_ID", nullable = false)
	public int getScopeId() {
		return this.scopeId;
	}

	public void setScopeId(int scopeId) {
		this.scopeId = scopeId;
	}

	@Column(name = "PRIORITY", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "SENTENCE", nullable = false, length = 500)
	public String getSentence() {
		return this.sentence;
	}

	public void setSentence(String sentence) {
		this.sentence = sentence;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
